### ISSUE TITLE
Serve Authors

### ISSUE THREAD

**Issue by shtanaka** [CMPUT404F16T06/CMPUT404Project#2]

**Comment by shtanaka** [comment]
Serve the following urls:
/authors/create/ (This one will have to create also an entity of Django User with Login and password)
/authors/
/authors/[id]
/authors/[id]/update/

**Comment by gemmamarcinkoski** [comment]
/authors/ should be working by my knowledge but it isnt, error with 
" url(r'^socialnet/', include('socialnet.urls')),"  line

/authors/ is supposed to be list of all authors
/authors/[id] is supposed to be the authors public profile information?

from past views:
isnt the authors postings list only included on our wall?

first attempt done - but with errors.

**Comment by gemmamarcinkoski** [comment]
/authors/ is served!
authors/[id]
and authors/[id]/update not working yet for some reason

trying tonight
